name: "AutoUpdateRelease"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
    steps:
    # Auto update-release.
    # https://github.com/marketplace/actions/update-existing-release
    - name: update-existing-release
      uses: IsaacShelton/update-existing-release@v1.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: src/memlogger.h src/memlogger.cc README.md
